service: homekit-tasks-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
